name: PR - Closed
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  delete-s3:
    name: Delete S3 Website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    if: ${{ github.event.pull_request.head.repo.full_name == 'vapor/blog' && github.event.pull_request.user.login != 'dependabot[bot]' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.OIDC_ROLE_REGION }}
      - name: Delete Website Bucket
        uses: brokenhandsio/s3-website-pr-action@6ebd9b622b4bb33358228571a50e05d375cbd4de # v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bucket-prefix: "vapor-blog-pulls"
          bucket-region: "us-east-1"
